services:
  db:
    image: postgres:16-alpine
    container_name: expense_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d expense_tracker"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: expense_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: andikaananda63@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
  
  backend:
    build: .
    container_name: expense_tracker_backend
    restart: unless-stopped
    env_file:
      - .env  
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=expense_tracker
      - DB_SSLMODE=disable
      - DB_TIMEZONE=Asia/Jakarta
      - APP_PORT=8081

volumes:
  pgdata:
